version: "1"
rules:
  - base: lts
    upstream: main
    mergeMethod: merge
    mergeUnstable: false
    reviewers:
      - castrojo
      - tulilirockz
    conflictReviewers:
      - castrojo
      - tulilirockz
label: "promotion"
conflictLabel: "promotion-conflict"
