name: Build Bluefin LTS HWE

permissions:
  contents: read
  packages: write
  id-token: write

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 1 * * TUE" # Every Tuesday at 1am UTC
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/reusable-build-image.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      image-name: bluefin
      rechunk: ${{ github.event_name != 'pull_request' }}
      sbom: ${{ github.event_name != 'pull_request' }}
      publish: ${{ github.event_name != 'pull_request' }}
      hwe: true
  tag:
    runs-on: ubuntu-latest
    needs: build
    permissions: 
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image from registry
        run: |
          echo "Pulling hwe image from registry"
          docker pull ghcr.io/${{ github.repository_owner }}/bluefin:lts-hwe

      - name: Tag image
        id: tag
        run: |
          echo "Tagging hwe image with testing suffix"
          docker tag ghcr.io/${{ github.repository_owner }}/bluefin:lts-hwe ghcr.io/${{ github.repository_owner }}/bluefin:lts-testing

      - name: Push tagged image
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          echo "Pushing tagged image"
          docker push ghcr.io/${{ github.repository_owner }}/bluefin:lts-testing
